# Dataset và DataLoader

In [1]:
import torch
from torch.utils.data import DataLoader, Dataset

# Tạo Dataset đơn giản
class MyDataset(Dataset):
    def __init__(self):
        self.data = list(range(10))  # Giả sử dữ liệu chỉ là danh sách số

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

# Khởi tạo Dataset
dataset = MyDataset()

# Tạo DataLoader
dataloader = DataLoader(dataset, batch_size=3, shuffle=True)

# Duyệt qua DataLoader
for batch in dataloader:
    print(batch)


tensor([6, 9, 2])
tensor([4, 0, 3])
tensor([1, 5, 7])
tensor([8])
